---
- name: (Debian) Add WireGuard repository on buster
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: "{{ 'present' if (ansible_distribution_version | int <= 10) else 'absent' }}"
    update_cache: yes
  become: true
  tags:
    - wg-install

- name: (Debian) Install kernel headers for the currently running kernel to compile Wireguard with DKMS
  apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
    state: present
  become: true

- name: (Debian) Get architecture
  command: "dpkg --print-architecture"
  register: wireguard__fact_dpkg_arch
  become: true
  changed_when: False

- name: (Debian) Install kernel headers metapackage to ensure headers will be installed
  apt:
    name:
      - "linux-headers-{{ wireguard__fact_dpkg_arch.stdout }}"
    state: present
  become: true
  when: ('-cloud-' not in ansible_kernel)

- name: (Debian) Install WireGuard packages
  apt:
    name:
      - "wireguard"
    state: present
  become: true
  tags:
    - wg-install
