---

- include_tasks: "setup-debian-raspbian.yml"
  when: ansible_lsb.id is defined and ansible_lsb.id == "Raspbian"
  register: wireguard__register_raspbian_setup
  ignore_errors: true


- include_tasks: "setup-debian-vanilla.yml"
  when: wireguard__register_raspbian_setup is skipped or ansible_lsb.id is undefined
